name: Sync to Gitee

on:
  push:
    branches: [master, gh-pages]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Sync to Gitee
        uses: wearerequired/git-mirror-action@master
        env:
          # 在 Settings->Secrets 配置 GITEE_PRIVATE_KEY
          SSH_PRIVATE_KEY: ${{ secrets.GITEE_PRIVATE_KEY }}
        with:
          # GitHub 源仓库地址
          source-repo: git@github.com:ytking/ytking.git
          # Gitee 目标仓库地址
          destination-repo: git@gitee.com:ytanck/ytanck.git
